/// The in-app logo: the app icon artwork.
///
/// The launcher icon and this logo are the same picture, generated from
/// `tool/icon/app_icon.png` (see `tool/make_icons.py` and the note in
/// `pubspec.yaml`). Keeping one asset for both places that draw it — the welcome
/// hero and the drawer header — means the screen the user opens and the icon they
/// tapped on always match.
library;

import 'package:flutter/material.dart';

/// Path of the bundled logo. Generated by downscaling `tool/icon/app_icon.png`.
const String kAppLogoAsset = 'assets/logo.png';

/// The logo in a rounded square of [size] logical pixels.
///
/// The artwork carries its own near-white background, so it is clipped rather
/// than blended: whatever sits behind it shows only at the corners, which is what
/// keeps the drawer's coloured badge looking like a badge.
class AppLogo extends StatelessWidget {
  const AppLogo({super.key, required this.size, this.radius = 9});

  final double size;
  final double radius;

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(radius),
      child: Image.asset(
        kAppLogoAsset,
        width: size,
        height: size,
        fit: BoxFit.cover,
        filterQuality: FilterQuality.medium,
      ),
    );
  }
}
