"""Regenerate the Android launcher icons from the source art.

The art is `tool/icon/app_icon.png` (1023x1023, an opaque white background). This
writes both halves of an Android icon set:

  * **Legacy PNGs** (`mipmap-*/ic_launcher.png`, 48..192px) for launchers that do
    not understand adaptive icons. The art is used as-is: it already has margins,
    so a launcher that masks it square, round or squircle keeps the character.
  * **Adaptive icons** (API 26+): a transparent `ic_launcher_foreground.png` per
    density plus `mipmap-anydpi-v26/ic_launcher.xml`. The foreground is scaled into
    the 66dp safe zone of the 108dp canvas, so no mask shape can clip the
    character; the background is the art's own background colour, which makes the
    foreground's square edge invisible.

Run it with any Python that has Pillow (the DSH runtime does):

    python app/tool/make_icons.py

It is idempotent: everything it writes is derived from the source art, so the
icons can always be traced back to one file instead of being hand-edited PNGs.
"""

from __future__ import annotations

import pathlib
import sys

from PIL import Image

APP = pathlib.Path(__file__).resolve().parent.parent
SOURCE = APP / "tool" / "icon" / "app_icon.png"
RES = APP / "android" / "app" / "src" / "main" / "res"

# Legacy launcher sizes, by Android density bucket.
LEGACY = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}

# Adaptive icons: the drawable is 108dp, of which the central 66dp is guaranteed
# visible under every mask. 70dp is a deliberate middle ground — the art carries
# its own margin, so the extra 2dp per side only ever eats background.
ADAPTIVE = {
    "mipmap-mdpi": 108,
    "mipmap-hdpi": 162,
    "mipmap-xhdpi": 216,
    "mipmap-xxhdpi": 324,
    "mipmap-xxxhdpi": 432,
}
ADAPTIVE_ART_DP = 70
ADAPTIVE_CANVAS_DP = 108

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/make_icons.py from tool/icon/app_icon.png. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""

COLORS_XML = """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Generated by tool/make_icons.py: the launcher icon's background, sampled
         from the source art so the adaptive foreground's square edge is invisible. -->
    <color name="ic_launcher_background">#{background}</color>
</resources>
"""


def background_colour(image: Image.Image) -> tuple[int, int, int]:
    """The art's own background, sampled from its four corners."""
    width, height = image.size
    corners = [
        image.getpixel((1, 1)),
        image.getpixel((width - 2, 1)),
        image.getpixel((1, height - 2)),
        image.getpixel((width - 2, height - 2)),
    ]
    channels = [sum(corner[index] for corner in corners) // len(corners) for index in range(3)]
    return channels[0], channels[1], channels[2]


def square(image: Image.Image, size: int) -> Image.Image:
    return image.resize((size, size), Image.LANCZOS)


def main() -> int:
    if not SOURCE.exists():
        print(f"missing source art: {SOURCE}")
        return 2

    art = Image.open(SOURCE).convert("RGBA")
    background = background_colour(art)
    hex_background = "".join(f"{channel:02X}" for channel in background)
    print(f"source {art.size[0]}x{art.size[1]}, background #{hex_background}")

    for bucket, size in LEGACY.items():
        target = RES / bucket / "ic_launcher.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        square(art, size).convert("RGB").save(target, "PNG", optimize=True)
        print(f"  {bucket}/ic_launcher.png            {size}x{size}")

    for bucket, canvas in ADAPTIVE.items():
        target = RES / bucket / "ic_launcher_foreground.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        art_size = round(canvas * ADAPTIVE_ART_DP / ADAPTIVE_CANVAS_DP)
        layer = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
        layer.paste(square(art, art_size), ((canvas - art_size) // 2, (canvas - art_size) // 2))
        layer.save(target, "PNG", optimize=True)
        print(f"  {bucket}/ic_launcher_foreground.png {canvas}x{canvas} (art {art_size}px)")

    adaptive_dir = RES / "mipmap-anydpi-v26"
    adaptive_dir.mkdir(parents=True, exist_ok=True)
    (adaptive_dir / "ic_launcher.xml").write_text(ADAPTIVE_XML, encoding="utf8")
    print("  mipmap-anydpi-v26/ic_launcher.xml")

    values = RES / "values" / "colors.xml"
    values.parent.mkdir(parents=True, exist_ok=True)
    values.write_text(COLORS_XML.format(background=hex_background), encoding="utf8")
    print(f"  values/colors.xml (ic_launcher_background #{hex_background})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
